stages:
  - build
  - deploy

build_images:
  stage: build
  tags:
    - build
  image: docker:latest
  script:
    - echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USER" --password-stdin
    # Build & Push Backend
    - docker build -no-cache --network host -t $DOCKERHUB_USER/shop-be:latest -f ./WebAPI/WebAPI/Dockerfile .
    - docker push $DOCKERHUB_USER/shop-be:latest
    # Build & Push Frontend
    - docker build -t $DOCKERHUB_USER/shop-admin:latest -f ./admin/Dockerfile .
    - docker push $DOCKERHUB_USER/shop-admin:latest
    - docker build -t $DOCKERHUB_USER/shop-user:latest -f ./user/Dockerfile .
    - docker push $DOCKERHUB_USER/shop-user:latest

deploy_to_server:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP "
        cd /home/project && 
        docker-compose pull && 
        docker-compose up -d"