stages:
  - build
  - deploy
  - checklog

variables:
  DOCKER_HUB_USER: $DOCKER_HUB_USER

# --- STAGE 1: BUILD ---
build_images:
  stage: build
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  script:
    - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USER" --password-stdin
    # Build Backend
    - echo "Building Backend..."
    - docker build -t $DOCKER_HUB_USER/ecommerce-backend:latest -f ./WebAPI/Dockerfile .
    - docker push $DOCKER_HUB_USER/ecommerce-backend:latest
    # Build Admin
    - echo "Building Admin..."
    - docker build -t $DOCKER_HUB_USER/ecommerce-admin:latest -f ./admin/Dockerfile .
    - docker push $DOCKER_HUB_USER/ecommerce-admin:latest
    # Build User
    - echo "Building Frontend User..."
    - docker build -t $DOCKER_HUB_USER/ecommerce-frontend:latest -f ./user/Dockerfile .
    - docker push $DOCKER_HUB_USER/ecommerce-frontend:latest
  tags:
    - build

# --- STAGE 2: DEPLOY ---
deploy_app:
  stage: deploy
  script:
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
    - cd /opt/mobile-ecommerce
    - docker compose pull
    - docker compose up -d
    - echo "Waiting for SQL Server to start..."
    - sleep 30
    - docker exec mssql-server /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P 'YourStrongPassword123!' -i /usr/config/init.sql
  tags:
    - deploy-runner

# --- STAGE 3: CHECKLOG ---
check_status:
  stage: checklog
  script:
    - docker ps
    - echo "--- LOGS BACKEND ---"
    - docker logs --tail 20 wbdt-server
  tags:
    - deploy-server
