build_frontend_admin:
  stage: build
  tags:
    - build
  image: docker:latest
  before_script:
    - echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USER" --password-stdin
  script:
    - docker build --network host -t $DOCKERHUB_USER/shop-admin:latest -f ./admin/Dockerfile .
    - docker push $DOCKERHUB_USER/shop-admin:latest
  rules:
    - changes:
        - admin/**/*