stages:
  - build
  - deploy
  - checklog

variables:
  DOCKER_HUB_USER: "kiin04"

# --- STAGE 1: BUILD ---
build_images:
  stage: build
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  script:
    - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USER" --password-stdin
    # Build Backend
    - cd WebAPI && docker build -t $DOCKER_HUB_USER/wbdt-server:latest . && docker push $DOCKER_HUB_USER/wbdt-server:latest && cd ..
    # Build Admin
    - cd admin && docker build -t $DOCKER_HUB_USER/wbdt-admin:latest . && docker push $DOCKER_HUB_USER/wbdt-admin:latest && cd ..
    # Build User
    - cd user && docker build -t $DOCKER_HUB_USER/wbdt-user:latest . && docker push $DOCKER_HUB_USER/wbdt-user:latest
  tags:
    - build

# --- STAGE 2: DEPLOY ---
deploy_app:
  stage: deploy
  script:
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
    - docker pull $DOCKER_HUB_USER/wbdt-server:latest
    - docker pull $DOCKER_HUB_USER/wbdt-admin:latest
    - docker pull $DOCKER_HUB_USER/wbdt-user:latest
    - docker rm -f wbdt-server wbdt-admin wbdt-user || true
    - docker run --name wbdt-server -dp 5000:80 $DOCKER_HUB_USER/wbdt-server:latest
    - docker run --name wbdt-admin -dp 5174:80 $DOCKER_HUB_USER/wbdt-admin:latest
    - docker run --name wbdt-user -dp 5173:80 $DOCKER_HUB_USER/wbdt-user:latest
  tags:
    - deploy-runner

# --- STAGE 3: CHECKLOG ---
check_status:
  stage: checklog
  script:
    - docker ps
    - docker logs --tail 20 wbdt-server
  tags:
    - deploy-runner